export { test_script, test_script_answers } from './test_script'
export { monday_script, monday_script_answers } from './monday_script'
export { tuesday_script, tuesday_script_answers } from './tuesday_script'
export { wednesday_script, wednesday_script_answers } from './wednesday_script'
export { thursday_script, thursday_script_answers } from './thursday_script'
export { friday_script, } from './friday_script'
