
  stages:
    - build
    - test
    - deploy

  default:
    image: maven:latest

  build:
    stage: build
    script:
      - mvn compile
    artifacts:
      paths:
        - target


  test-all:
    stage: test
    except:
    - master
    script:
    - mvn clean install

  test-unit:
    stage: test
    only:
      - master
    script:
      - echo "Executing SpringBoot scenarios with maven"
      - mvn clean package
      - cp target/chronokill-spring-app*.jar chronokill-spring-app-${CI_COMMIT_SHA}.jar
    artifacts:
      when: always
      name: chronokill-spring-app
      paths:
        - chronokill-spring-app-${CI_COMMIT_SHA}.jar
      expire_in: 24 h

  deploy:
    stage: deploy
    needs: [test-unit]
    only:
    - master
    script:
    - ls chronokill-spring-app-${CI_COMMIT_SHA}.jar